name: amap_core_fluttify
description: An `Amap` Core Component, Powered By `Fluttify` Engine, Which Generates Dart Interface For Native SDK.
version: 0.5.1+6777f7f
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_core_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin